export const mockPlaces = [
    {
      id: "1",
      name: "Central Park",
      rating: 4.8,
      image: 'https://picsum.photos/400/200',
      description: "Beautiful park perfect for outdoor activities",
      distance: "0.5 km",
      address: "123 Park Avenue, New York",
      openingHours: "6:00 AM - 10:00 PM",
      features: ["Walking Trails", "Playground", "Lake"],
      tags: ["outdoor", "nature", "family-friendly", "morning", "easy"],
      difficulty: "easy",
      duration: "2-3 hours",
      timeOfDay: "morning"
    },
    {
      id: "2", 
      name: "Metropolitan Museum of Art",
      rating: 4.5,
      image: 'https://picsum.photos/400/201',
      description: "World-class art exhibitions and cultural experiences",
      distance: "1.2 km",
      address: "456 Museum Road, New York",
      openingHours: "9:00 AM - 6:00 PM",
      features: ["Exhibitions", "Guided Tours", "Gift Shop"],
      tags: ["indoor", "cultural", "art", "afternoon", "moderate"],
      difficulty: "moderate",
      duration: "3-4 hours",
      timeOfDay: "afternoon"
    },
    {
      id: "3",
      name: "High Line",
      rating: 4.7,
      image: 'https://picsum.photos/400/202',
      description: "Elevated park with urban gardens and art installations",
      distance: "2.1 km",
      address: "789 Garden Street, New York",
      openingHours: "7:00 AM - 10:00 PM", 
      features: ["Urban Garden", "Art Installations", "Food Vendors"],
      tags: ["outdoor", "urban", "art", "evening", "easy"],
      difficulty: "easy",
      duration: "1-2 hours",
      timeOfDay: "evening"
    },
    {
      id: "4",
      name: "Rock Climbing Gym",
      rating: 4.6,
      image: 'https://picsum.photos/400/203',
      description: "Indoor climbing facility with routes for all skill levels",
      distance: "3.0 km",
      address: "321 Sports Ave, New York",
      openingHours: "6:00 AM - 11:00 PM",
      features: ["Bouldering", "Top Rope", "Training Area"],
      tags: ["indoor", "adventure", "sports", "afternoon", "challenging"],
      difficulty: "challenging",
      duration: "2-3 hours",
      timeOfDay: "afternoon"
    },
    {
      id: "5",
      name: "Riverside Bike Trail",
      rating: 4.4,
      image: 'https://picsum.photos/400/204',
      description: "Scenic riverside cycling path with great views",
      distance: "1.8 km",
      address: "444 Riverside Dr, New York",
      openingHours: "24/7",
      features: ["Bike Path", "River Views", "Rest Areas"],
      tags: ["outdoor", "adventure", "sports", "morning", "moderate"],
      difficulty: "moderate",
      duration: "1-2 hours",
      timeOfDay: "morning"
    }
  ];