import { Activity } from "@/types/types";

export const mockPlaces: Activity[] = [
  {
    id: "1",
    name: "Mountain Peak Trail",
    rating: 4.8,
    image: "https://picsum.photos/seed/mountain/800/600",
    description:
      "A scenic hiking trail offering breathtaking mountain views and diverse wildlife encounters.",
    distance: "5.2 km",
    address: "123 Mountain Ridge Road, Adventure Valley",
    openingHours: "Dawn to Dusk",
    features: [
      "Scenic Views",
      "Wildlife Spotting",
      "Rest Areas",
      "Marked Trail",
    ],
    tags: ["adventure", "hiking", "outdoor", "nature"],
    difficulty: "moderate",
    duration: "medium",
    timeOfDay: "morning",
    phone: "+1-555-0123",
    website: "www.mountainpeaktrail.com",
  },
  {
    id: "2",
    name: "Blue Lagoon Kayaking",
    rating: 4.7,
    image: "https://picsum.photos/seed/kayak/800/600",
    description:
      "Explore crystal clear waters and hidden coves through guided kayaking tours.",
    distance: "3.1 km",
    address: "45 Coastal Drive, Marina Bay",
    openingHours: "8:00 AM - 6:00 PM",
    features: [
      "Equipment Rental",
      "Guided Tours",
      "Safety Training",
      "Storage Lockers",
    ],
    tags: ["adventure", "water", "kayaking", "outdoor"],
    difficulty: "easy",
    duration: "short",
    timeOfDay: "morning",
    phone: "+1-555-0124",
    website: "www.bluelagoonkayaking.com",
  },
  {
    id: "3",
    name: "Cultural Heritage Museum",
    rating: 4.6,
    image: "https://picsum.photos/seed/museum/800/600",
    description:
      "Immerse yourself in local history and cultural artifacts spanning centuries.",
    distance: "1.5 km",
    address: "789 History Lane, Old Town",
    openingHours: "9:00 AM - 5:00 PM",
    features: ["Guided Tours", "Interactive Exhibits", "Café", "Gift Shop"],
    tags: ["culture", "museum", "indoor", "history"],
    difficulty: "easy",
    duration: "medium",
    timeOfDay: "midday",
    phone: "+1-555-0125",
    website: "www.heritagemuseum.com",
  },
  {
    id: "4",
    name: "Sunset Beach Yoga",
    rating: 4.9,
    image: "https://picsum.photos/seed/beach/800/600",
    description:
      "Rejuvenating yoga sessions with ocean views and calming sea breeze.",
    distance: "2.3 km",
    address: "321 Beachfront Avenue, Coastal Haven",
    openingHours: "6:00 AM - 8:00 PM",
    features: [
      "Mat Rental",
      "Professional Instructors",
      "Meditation Area",
      "Changing Rooms",
    ],
    tags: ["relax", "yoga", "beach", "wellness"],
    difficulty: "easy",
    duration: "short",
    timeOfDay: "sunset",
    phone: "+1-555-0126",
    website: "www.sunsetyoga.com",
  },
  {
    id: "5",
    name: "Local Flavors Food Tour",
    rating: 4.8,
    image: "https://picsum.photos/seed/food/800/600",
    description:
      "Sample the best local cuisine through guided walking food tours.",
    distance: "0.8 km",
    address: "567 Foodie Street, Downtown",
    openingHours: "11:00 AM - 9:00 PM",
    features: [
      "Multiple Tastings",
      "Expert Guide",
      "Cultural Insights",
      "Dietary Options",
    ],
    tags: ["food", "local", "culture", "walking"],
    difficulty: "easy",
    duration: "medium",
    timeOfDay: "afternoon",
    phone: "+1-555-0127",
    website: "www.localflavors.com",
  },
  {
    id: "6",
    name: "Rock Climbing Adventure",
    rating: 4.7,
    image: "https://picsum.photos/seed/climbing/800/600",
    description: "Professional rock climbing experiences for all skill levels.",
    distance: "7.5 km",
    address: "890 Rocky Road, Adventure Peak",
    openingHours: "8:00 AM - 6:00 PM",
    features: [
      "Equipment Rental",
      "Safety Training",
      "Expert Guides",
      "Multiple Routes",
    ],
    tags: ["adventure", "climbing", "outdoor", "active"],
    difficulty: "challenging",
    duration: "medium",
    timeOfDay: "morning",
    phone: "+1-555-0128",
    website: "www.rockclimbingadventure.com",
  },
  {
    id: "7",
    name: "Jazz & Blues Club",
    rating: 4.6,
    image: "https://picsum.photos/seed/jazz/800/600",
    description:
      "Live music venue featuring local and international jazz artists.",
    distance: "1.2 km",
    address: "234 Music Avenue, Entertainment District",
    openingHours: "7:00 PM - 2:00 AM",
    features: ["Live Music", "Full Bar", "Table Service", "Food Menu"],
    tags: ["nightlife", "music", "entertainment", "indoor"],
    difficulty: "easy",
    duration: "long",
    timeOfDay: "night",
    phone: "+1-555-0129",
    website: "www.jazzbluesclub.com",
  },
  {
    id: "8",
    name: "Thermal Springs Spa",
    rating: 4.9,
    image: "https://picsum.photos/seed/spa/800/600",
    description:
      "Natural thermal springs with therapeutic properties and spa services.",
    distance: "4.7 km",
    address: "678 Wellness Way, Spa Valley",
    openingHours: "9:00 AM - 10:00 PM",
    features: [
      "Thermal Pools",
      "Massage Services",
      "Sauna",
      "Relaxation Areas",
    ],
    tags: ["relax", "spa", "wellness", "thermal"],
    difficulty: "easy",
    duration: "medium",
    timeOfDay: "afternoon",
    phone: "+1-555-0130",
    website: "www.thermalsprings.com",
  },
  {
    id: "9",
    name: "Mountain Biking Trails",
    rating: 4.7,
    image: "https://picsum.photos/seed/biking/800/600",
    description:
      "Extensive network of mountain biking trails for all skill levels.",
    distance: "6.3 km",
    address: "901 Trail Head Road, Mountain Park",
    openingHours: "Sunrise to Sunset",
    features: ["Bike Rental", "Trail Maps", "Repair Station", "Rest Areas"],
    tags: ["adventure", "cycling", "outdoor", "active"],
    difficulty: "moderate",
    duration: "medium",
    timeOfDay: "morning",
    phone: "+1-555-0131",
    website: "www.mountainbiketrails.com",
  },
  {
    id: "10",
    name: "Artisan Market & Workshops",
    rating: 4.5,
    image: "https://picsum.photos/seed/market/800/600",
    description:
      "Local artisan market featuring handmade crafts and interactive workshops.",
    distance: "1.8 km",
    address: "432 Craft Lane, Arts District",
    openingHours: "10:00 AM - 7:00 PM",
    features: ["Workshops", "Local Products", "Demonstrations", "Café"],
    tags: ["culture", "shopping", "arts", "local"],
    difficulty: "easy",
    duration: "short",
    timeOfDay: "midday",
    phone: "+1-555-0132",
    website: "www.artisanmarket.com",
  },
];
