import { Activity } from "@/types/types";

type LocalizedActivity = {
  en: Activity[];
  he: Activity[];
};

export const mockPlaces: LocalizedActivity = {
  en: [
    {
      id: "1",
      name: "Mountain Peak Trail",
      rating: 4.8,
      image: "https://picsum.photos/seed/mountain/800/600",
      description: "A scenic hiking trail offering breathtaking mountain views and diverse wildlife encounters.",
      distance: "5.2 km",
      address: "123 Mountain Ridge Road, Adventure Valley",
      openingHours: "Dawn to Dusk",
      features: ["Scenic Views", "Wildlife Spotting", "Rest Areas", "Marked Trail"],
      tags: ["adventure", "hiking", "outdoor", "nature"],
      difficulty: "moderate",
      duration: "medium",
      timeOfDay: "morning",
      phone: "+1-555-0123",
      website: "www.mountainpeaktrail.com",
    },
    {
      id: "2",
      name: "Blue Lagoon Kayaking",
      rating: 4.7,
      image: "https://picsum.photos/seed/kayak/800/600",
      description:
        "Explore crystal clear waters and hidden coves through guided kayaking tours.",
      distance: "3.1 km",
      address: "45 Coastal Drive, Marina Bay",
      openingHours: "8:00 AM - 6:00 PM",
      features: [
        "Equipment Rental",
        "Guided Tours",
        "Safety Training",
        "Storage Lockers",
      ],
      tags: ["adventure", "water", "kayaking", "outdoor"],
      difficulty: "easy",
      duration: "short",
      timeOfDay: "morning",
      phone: "+1-555-0124",
      website: "www.bluelagoonkayaking.com",
    },
    {
      id: "3",
      name: "Cultural Heritage Museum",
      rating: 4.6,
      image: "https://picsum.photos/seed/museum/800/600",
      description:
        "Immerse yourself in local history and cultural artifacts spanning centuries.",
      distance: "1.5 km",
      address: "789 History Lane, Old Town",
      openingHours: "9:00 AM - 5:00 PM",
      features: ["Guided Tours", "Interactive Exhibits", "Café", "Gift Shop"],
      tags: ["culture", "museum", "indoor", "history"],
      difficulty: "easy",
      duration: "medium",
      timeOfDay: "midday",
      phone: "+1-555-0125",
      website: "www.heritagemuseum.com",
    },
    {
      id: "4",
      name: "Sunset Beach Yoga",
      rating: 4.9,
      image: "https://picsum.photos/seed/beach/800/600",
      description:
        "Rejuvenating yoga sessions with ocean views and calming sea breeze.",
      distance: "2.3 km",
      address: "321 Beachfront Avenue, Coastal Haven",
      openingHours: "6:00 AM - 8:00 PM",
      features: [
        "Mat Rental",
        "Professional Instructors",
        "Meditation Area",
        "Changing Rooms",
      ],
      tags: ["relax", "yoga", "beach", "wellness"],
      difficulty: "easy",
      duration: "short",
      timeOfDay: "sunset",
      phone: "+1-555-0126",
      website: "www.sunsetyoga.com",
    },
    {
      id: "5",
      name: "Local Flavors Food Tour",
      rating: 4.8,
      image: "https://picsum.photos/seed/food/800/600",
      description:
        "Sample the best local cuisine through guided walking food tours.",
      distance: "0.8 km",
      address: "567 Foodie Street, Downtown",
      openingHours: "11:00 AM - 9:00 PM",
      features: [
        "Multiple Tastings",
        "Expert Guide",
        "Cultural Insights",
        "Dietary Options",
      ],
      tags: ["food", "local", "culture", "walking"],
      difficulty: "easy",
      duration: "medium",
      timeOfDay: "afternoon",
      phone: "+1-555-0127",
      website: "www.localflavors.com",
    },
    {
      id: "6",
      name: "Rock Climbing Adventure",
      rating: 4.7,
      image: "https://picsum.photos/seed/climbing/800/600",
      description: "Professional rock climbing experiences for all skill levels.",
      distance: "7.5 km",
      address: "890 Rocky Road, Adventure Peak",
      openingHours: "8:00 AM - 6:00 PM",
      features: [
        "Equipment Rental",
        "Safety Training",
        "Expert Guides",
        "Multiple Routes",
      ],
      tags: ["adventure", "climbing", "outdoor", "active"],
      difficulty: "challenging",
      duration: "medium",
      timeOfDay: "morning",
      phone: "+1-555-0128",
      website: "www.rockclimbingadventure.com",
    },
    {
      id: "7",
      name: "Jazz & Blues Club",
      rating: 4.6,
      image: "https://picsum.photos/seed/jazz/800/600",
      description:
        "Live music venue featuring local and international jazz artists.",
      distance: "1.2 km",
      address: "234 Music Avenue, Entertainment District",
      openingHours: "7:00 PM - 2:00 AM",
      features: ["Live Music", "Full Bar", "Table Service", "Food Menu"],
      tags: ["nightlife", "music", "entertainment", "indoor"],
      difficulty: "easy",
      duration: "long",
      timeOfDay: "night",
      phone: "+1-555-0129",
      website: "www.jazzbluesclub.com",
    },
    {
      id: "8",
      name: "Thermal Springs Spa",
      rating: 4.9,
      image: "https://picsum.photos/seed/spa/800/600",
      description:
        "Natural thermal springs with therapeutic properties and spa services.",
      distance: "4.7 km",
      address: "678 Wellness Way, Spa Valley",
      openingHours: "9:00 AM - 10:00 PM",
      features: [
        "Thermal Pools",
        "Massage Services",
        "Sauna",
        "Relaxation Areas",
      ],
      tags: ["relax", "spa", "wellness", "thermal"],
      difficulty: "easy",
      duration: "medium",
      timeOfDay: "afternoon",
      phone: "+1-555-0130",
      website: "www.thermalsprings.com",
    },
    {
      id: "9",
      name: "Mountain Biking Trails",
      rating: 4.7,
      image: "https://picsum.photos/seed/biking/800/600",
      description:
        "Extensive network of mountain biking trails for all skill levels.",
      distance: "6.3 km",
      address: "901 Trail Head Road, Mountain Park",
      openingHours: "Sunrise to Sunset",
      features: ["Bike Rental", "Trail Maps", "Repair Station", "Rest Areas"],
      tags: ["adventure", "cycling", "outdoor", "active"],
      difficulty: "moderate",
      duration: "medium",
      timeOfDay: "morning",
      phone: "+1-555-0131",
      website: "www.mountainbiketrails.com",
    },
    {
      id: "10",
      name: "Artisan Market & Workshops",
      rating: 4.5,
      image: "https://picsum.photos/seed/market/800/600",
      description:
        "Local artisan market featuring handmade crafts and interactive workshops.",
      distance: "1.8 km",
      address: "432 Craft Lane, Arts District",
      openingHours: "10:00 AM - 7:00 PM",
      features: ["Workshops", "Local Products", "Demonstrations", "Café"],
      tags: ["culture", "shopping", "arts", "local"],
      difficulty: "easy",
      duration: "short",
      timeOfDay: "midday",
      phone: "+1-555-0132",
      website: "www.artisanmarket.com",
    },
  ],
  he: [
    {
      id: "1",
      name: "שביל פסגת ההר",
      rating: 4.8,
      image: "https://picsum.photos/seed/mountain/800/600",
      description: "מסלול הליכה נופי המציע נופים עוצרי נשימה ומפגשים עם חיות בר מגוונות.",
      distance: "5.2 ק״מ",
      address: "רחוב רכס ההר 123, עמק ההרפתקאות",
      openingHours: "מזריחה עד שקיעה",
      features: ["נופים מרהיבים", "צפייה בחיות בר", "אזורי מנוחה", "שביל מסומן"],
      tags: ["הרפתקה", "טיולים", "חוץ", "טבע"],
      difficulty: "בינוני",
      duration: "בינוני",
      timeOfDay: "בוקר",
      phone: "+1-555-0123",
      website: "www.mountainpeaktrail.com",
    },
    {
      id: "2",
      name: "קיאקים בלגונה הכחולה",
      rating: 4.7,
      image: "https://picsum.photos/seed/kayak/800/600",
      description: "חקרו מים צלולים ומפרצים נסתרים בסיורי קיאקים מודרכים.",
      distance: "3.1 ק״מ",
      address: "דרך החוף 45, מרינה ביי",
      openingHours: "8:00 - 18:00",
      features: ["השכרת ציוד", "סיורים מודרכים", "הדרכת בטיחות", "תאי אחסון"],
      tags: ["הרפתקה", "מים", "קיאקים", "חוץ"],
      difficulty: "קל",
      duration: "קצר",
      timeOfDay: "בוקר",
      phone: "+1-555-0124",
      website: "www.bluelagoonkayaking.com",
    },
    {
      id: "3",
      name: "מוזיאון המורשת התרבותית",
      rating: 4.6,
      image: "https://picsum.photos/seed/museum/800/600",
      description: "צללו אל תוך ההיסטוריה המקומית ופריטי תרבות מלפני מאות שנים.",
      distance: "1.5 ק״מ",
      address: "סמטת ההיסטוריה 789, העיר העתיקה",
      openingHours: "9:00 - 17:00",
      features: ["סיורים מודרכים", "תצוגות אינטראקטיביות", "בית קפה", "חנות מזכרות"],
      tags: ["תרבות", "מוזיאון", "פנים", "היסטוריה"],
      difficulty: "קל",
      duration: "בינוני",
      timeOfDay: "צהריים",
      phone: "+1-555-0125",
      website: "www.heritagemuseum.com",
    },
    {
      id: "4",
      name: "יוגה בשקיעה בחוף",
      rating: 4.9,
      image: "https://picsum.photos/seed/beach/800/600",
      description: "שיעורי יוגה מרעננים עם נוף לאוקיינוס ורוח ים מרגיעה.",
      distance: "2.3 ק״מ",
      address: "שדרות חוף הים 321, מפרץ החוף",
      openingHours: "6:00 - 20:00",
      features: ["השכרת מזרנים", "מדריכים מקצועיים", "אזור מדיטציה", "חדרי הלבשה"],
      tags: ["רוגע", "יוגה", "חוף", "בריאות"],
      difficulty: "קל",
      duration: "קצר",
      timeOfDay: "שקיעה",
      phone: "+1-555-0126",
      website: "www.sunsetyoga.com",
    },
    {
      id: "5",
      name: "סיור טעימות מקומי",
      rating: 4.8,
      image: "https://picsum.photos/seed/food/800/600",
      description: "טעמו את המטבח המקומי הטוב ביותר בסיורי אוכל מודרכים.",
      distance: "0.8 ק״מ",
      address: "רחוב האוכל 567, מרכז העיר",
      openingHours: "11:00 - 21:00",
      features: ["טעימות מרובות", "מדריך מומחה", "תובנות תרבותיות", "אפשרויות תזונה"],
      tags: ["אוכל", "מקומי", "תרבות", "הליכה"],
      difficulty: "קל",
      duration: "בינוני",
      timeOfDay: "אחר הצהריים",
      phone: "+1-555-0127",
      website: "www.localflavors.com",
    },
    {
      id: "6",
      name: "הרפתקת טיפוס סלעים",
      rating: 4.7,
      image: "https://picsum.photos/seed/climbing/800/600",
      description: "חוויות טיפוס סלעים מקצועיות לכל רמות המיומנות.",
      distance: "7.5 ק״מ",
      address: "דרך הסלע 890, פסגת ההרפתקאות",
      openingHours: "8:00 - 18:00",
      features: ["השכרת ציוד", "הדרכת בטיחות", "מדריכים מומחים", "מסלולים מרובים"],
      tags: ["הרפתקה", "טיפוס", "חוץ", "פעיל"],
      difficulty: "מאתגר",
      duration: "בינוני",
      timeOfDay: "בוקר",
      phone: "+1-555-0128",
      website: "www.rockclimbingadventure.com",
    },
    {
      id: "7",
      name: "מועדון ג'אז ובלוז",
      rating: 4.6,
      image: "https://picsum.photos/seed/jazz/800/600",
      description: "מקום למוזיקה חיה המציג אמני ג'אז מקומיים ובינלאומיים.",
      distance: "1.2 ק״מ",
      address: "שדרות המוזיקה 234, רובע הבידור",
      openingHours: "19:00 - 02:00",
      features: ["מוזיקה חיה", "בר מלא", "שירות שולחן", "תפריט אוכל"],
      tags: ["חיי לילה", "מוזיקה", "בידור", "פנים"],
      difficulty: "קל",
      duration: "ארוך",
      timeOfDay: "לילה",
      phone: "+1-555-0129",
      website: "www.jazzbluesclub.com",
    },
    {
      id: "8",
      name: "ספא מעיינות חמים",
      rating: 4.9,
      image: "https://picsum.photos/seed/spa/800/600",
      description: "מעיינות חמים טבעיים עם תכונות טיפוליות ושירותי ספא.",
      distance: "4.7 ק״מ",
      address: "דרך הבריאות 678, עמק הספא",
      openingHours: "9:00 - 22:00",
      features: ["בריכות חמות", "שירותי עיסוי", "סאונה", "אזורי רגיעה"],
      tags: ["רוגע", "ספא", "בריאות", "מעיינות"],
      difficulty: "קל",
      duration: "בינוני",
      timeOfDay: "אחר הצהריים",
      phone: "+1-555-0130",
      website: "www.thermalsprings.com",
    },
    {
      id: "9",
      name: "שבילי אופני הרים",
      rating: 4.7,
      image: "https://picsum.photos/seed/biking/800/600",
      description: "רשת נרחבת של שבילי אופני הרים לכל רמות המיומנות.",
      distance: "6.3 ק״מ",
      address: "דרך ראש השביל 901, פארק ההר",
      openingHours: "מזריחה עד שקיעה",
      features: ["השכרת אופניים", "מפות שבילים", "תחנת תיקונים", "אזורי מנוחה"],
      tags: ["הרפתקה", "רכיבה", "חוץ", "פעיל"],
      difficulty: "בינוני",
      duration: "בינוני",
      timeOfDay: "בוקר",
      phone: "+1-555-0131",
      website: "www.mountainbiketrails.com",
    },
    {
      id: "10",
      name: "שוק אומנים וסדנאות",
      rating: 4.5,
      image: "https://picsum.photos/seed/market/800/600",
      description: "שוק אומנים מקומי המציג מלאכות יד וסדנאות אינטראקטיביות.",
      distance: "1.8 ק״מ",
      address: "סמטת האומנות 432, רובע האמנויות",
      openingHours: "10:00 - 19:00",
      features: ["סדנאות", "מוצרים מקומיים", "הדגמות", "בית קפה"],
      tags: ["תרבות", "קניות", "אמנות", "מקומי"],
      difficulty: "קל",
      duration: "קצר",
      timeOfDay: "צהריים",
      phone: "+1-555-0132",
      website: "www.artisanmarket.com",
    }
  ]
};

// Helper function to get activities based on current language
export const getLocalizedActivities = (language: 'en' | 'he'): Activity[] => {
  return mockPlaces[language];
};
